### ISSUE TITLE
Fails to compile a 'write to the Console' in c#

### ISSUE THREAD

**Issue by aabeyta** [gburgett/SnippetExecutor#13]
Here is the text I put in NP++: 
System.Console.WriteLine("it worked");

I have the c# language selected for the document.  Here is the error that I get:
--- SnippetExecutor 9:59 AM ---
-- Generating source for snippet...

-- compiling source with options 
Assemblies: System.dll System.Core.dll 
Compiled! C:\Users\AaronA\AppData\Local\Temp\emo4zkap.exe
Errors!
c:\Users\AaronA\AppData\Local\Temp\emo4zkap.0.cs(70,26) : error CS1519: Invalid token '(' in class, struct, or interface member declaration

**Comment by gburgett** [comment]
Mine works, I seem to remember that error being related to the snippet compiler thinking you're defining a function there.  I remember fixing that, make sure you're on the right version.  You should be on commit 8a29aa7c5a9abe562347937280635b3e0d7ffc33

**Comment by gburgett** [comment]
Accidentally hit comment & close, this is my first time using github.

**Comment by aabeyta** [comment]
Great!!  I upgraded to the new version and it works.
